export const socketErrorHandling = (fn) => {
    try {
        
    } catch (error) {
        
    }
};
